import { motion } from 'framer-motion'
import { Card, CardHeader, CardTitle, CardDescription } from '@/shared/components/ui/card'
import { Brain, Search, Layers, Activity } from 'lucide-react'

const features = [
  {
    title: "AI Image Detection",
    description: "Detect whether an image was generated by cutting-edge AI models like Midjourney, DALL-E, or Stable Diffusion.",
    icon: Brain,
    color: "text-purple-400"
  },
  {
    title: "Metadata Analysis",
    description: "Reveal hidden EXIF metadata like camera model, editing software, and timestamps to trace image origins.",
    icon: Search,
    color: "text-blue-400"
  },
  {
    title: "Manipulation Detection",
    description: "Error Level Analysis (ELA) highlights regions with different compression levels, indicating potential edits.",
    icon: Layers,
    color: "text-cyan-400"
  },
  {
    title: "Authenticity Score",
    description: "Receive a weighted authenticity score based on multi-signal analysis, providing a clear trust metric.",
    icon: Activity,
    color: "text-emerald-400"
  }
]

export default function Features() {
  return (
    <section id="features" className="py-32 bg-background relative overflow-hidden">
      <div className="container mx-auto px-6 relative z-10">
        <div className="text-center mb-24">
          <motion.h2 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-4xl md:text-5xl font-bold text-white mb-6"
          >
            Enterprise Forensic <span className="text-primary italic">Intelligence</span>
          </motion.h2>
          <motion.p 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1 }}
            className="text-muted-foreground max-w-2xl mx-auto text-lg"
          >
            ShadowMode combines multiple detection vectors to provide the most comprehensive 
            analysis of digital image authenticity.
          </motion.p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feature, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: idx * 0.1 }}
            >
              <Card className="glass-card h-full border-white/5 hover:border-primary/20 transition-all hover:translate-y-[-8px] group">
                <CardHeader className="p-8">
                  <div className={`size-14 rounded-2xl bg-white/[0.03] flex items-center justify-center mb-6 group-hover:bg-primary/10 transition-colors`}>
                    <feature.icon className={`size-7 ${feature.color}`} />
                  </div>
                  <CardTitle className="text-xl text-white mb-4">{feature.title}</CardTitle>
                  <CardDescription className="text-muted-foreground leading-relaxed leading-relaxed font-normal">
                    {feature.description}
                  </CardDescription>
                </CardHeader>
              </Card>
            </motion.div>
          ))}
        </div>
      </div>
      
      {/* Decorative elements */}
      <div className="absolute top-1/2 left-0 w-96 h-96 bg-primary/5 blur-[120px] rounded-full pointer-events-none" />
      <div className="absolute bottom-0 right-0 w-96 h-96 bg-primary/5 blur-[120px] rounded-full pointer-events-none" />
    </section>
  )
}
